# Generated by Django 4.2 on 2023-06-07 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NewsPortal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en_us',
            field=models.CharField(max_length=40, null=True, unique=True, verbose_name='catname'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=40, null=True, unique=True, verbose_name='catname'),
        ),
        migrations.AddField(
            model_name='post',
            name='author_en_us',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='post',
            name='author_ru',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='post',
            name='category_en_us',
            field=models.ManyToManyField(null=True, through='NewsPortal.PostCategory', to='NewsPortal.category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='post',
            name='category_ru',
            field=models.ManyToManyField(null=True, through='NewsPortal.PostCategory', to='NewsPortal.category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='post',
            name='rating_en_us',
            field=models.IntegerField(default=0, null=True, verbose_name='Rating'),
        ),
        migrations.AddField(
            model_name='post',
            name='rating_ru',
            field=models.IntegerField(default=0, null=True, verbose_name='Rating'),
        ),
        migrations.AddField(
            model_name='post',
            name='text_en_us',
            field=models.TextField(null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='post',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='post',
            name='time_in_en_us',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Time_in'),
        ),
        migrations.AddField(
            model_name='post',
            name='time_in_ru',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Time_in'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en_us',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='post',
            name='type_en_us',
            field=models.CharField(choices=[('AR', 'Статья'), ('NW', 'Новость')], max_length=7, null=True, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='post',
            name='type_ru',
            field=models.CharField(choices=[('AR', 'Статья'), ('NW', 'Новость')], max_length=7, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=40, unique=True, verbose_name='catname'),
        ),
        migrations.AlterField(
            model_name='category',
            name='subscribe',
            field=models.ManyToManyField(through='NewsPortal.CategorySubscribe', to=settings.AUTH_USER_MODEL, verbose_name='subscriber'),
        ),
        migrations.AlterField(
            model_name='categorysubscribe',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='NewsPortal.category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='categorysubscribe',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='subscriber'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(through='NewsPortal.PostCategory', to='NewsPortal.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='post',
            name='time_in',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Time_in'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('AR', 'Статья'), ('NW', 'Новость')], max_length=7, verbose_name='Type'),
        ),
        migrations.CreateModel(
            name='PostCategory_ru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NewsPortal.category')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NewsPortal.post')),
            ],
            options={
                'verbose_name': 'post category [ru]',
                'verbose_name_plural': 'post categorys [ru]',
                'db_table': 'NewsPortal_postcategory_ru',
                'db_tablespace': '',
                'auto_created': False,
            },
        ),
        migrations.CreateModel(
            name='PostCategory_en_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NewsPortal.category')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NewsPortal.post')),
            ],
            options={
                'verbose_name': 'post category [en-us]',
                'verbose_name_plural': 'post categorys [en-us]',
                'db_table': 'NewsPortal_postcategory_en_us',
                'db_tablespace': '',
                'auto_created': False,
            },
        ),
    ]
